services:
  # https://nginx.org/ - reverse proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    env_file: .env
    networks:
      - n8n_default
      - supabase_default

# a bit implicit but docker compose creates default networks based on the folder names (in the host)
# based on the `deploy.sh` script
# https://docs.docker.com/compose/how-tos/networking/
networks:
  n8n_default:
    external: true
  supabase_default:
    external: true